### ISSUE TITLE
Set up Heroku and deploy app

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#54]
### Acceptance Criteria

- [ ] Create an account for Heroku (details on which email to be covered in #50 )
- [ ] Ensure we are tracking properly
- [ ] Deploy the product
- [ ] Add the link to the Readme of this repo
- [ ] Provide any useful documentation on how to use Heroku and add to the #1 issue as a comment

**Comment by remaininlight** [comment]
Trying to build the database for staging with `npm run build:db` (https://dashboard.heroku.com/apps/hyde-dev) but getting error below. @RamyAlshurafa @cemalokten do you know how I can make it build the database please?

```
Error: relation "steps" does not exist
    at DatabaseError.<anonymous> (/app/server/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
    at new Error (/app/server/node_modules/core-js/modules/es.error.cause.js:28:43)
    at new DatabaseError (/app/server/node_modules/pg-protocol/src/messages.ts:115:5)
    at Parser.parseErrorMessage (/app/server/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/server/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/server/node_modules/pg-protocol/src/parser.ts:103:30)
    at TLSSocket.<anonymous> (/app/server/node_modules/pg-protocol/src/index.ts:7:48)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 103,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '433',
  routine: 'RangeVarGetRelidExtended'
```
